version: '3'

services:
  node:
    container_name: main
    restart: always
    build: .
    command: npm run start:dev
    image: juliapike/nodejs2022q4
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules/
    networks:
      - server-node


  postgres:
    container_name: postgres
    restart: always
    build: ./db/
    image: juliapike/nodejs2022q4:postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/pgdata:${PG_DATA}
    networks:
      - server-node

networks:
  server-node:
    driver: bridge